/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface StockPriceV1 {}
  interface StockPriceV1Attributes extends StencilHTMLAttributes {}

  interface UcStockPrice {
    'stockSymbol': any;
  }
  interface UcStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'StockPriceV1': Components.StockPriceV1;
    'UcStockPrice': Components.UcStockPrice;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'stock-price-v1': Components.StockPriceV1Attributes;
    'uc-stock-price': Components.UcStockPriceAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLStockPriceV1Element extends Components.StockPriceV1, HTMLStencilElement {}
  var HTMLStockPriceV1Element: {
    prototype: HTMLStockPriceV1Element;
    new (): HTMLStockPriceV1Element;
  };

  interface HTMLUcStockPriceElement extends Components.UcStockPrice, HTMLStencilElement {}
  var HTMLUcStockPriceElement: {
    prototype: HTMLUcStockPriceElement;
    new (): HTMLUcStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'stock-price-v1': HTMLStockPriceV1Element
    'uc-stock-price': HTMLUcStockPriceElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'stock-price-v1': HTMLStockPriceV1Element;
    'uc-stock-price': HTMLUcStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
